import { SalaryRecord, TaxDefinition } from "./types";

export const financeTaxDefinitionsSeed: TaxDefinition[] = [
  {
    id: "tax-income",
    name: "Income Tax",
    type: "percentage",
    value: 10,
    description: "Standard income tax applied to gross salary.",
    active: true,
  },
  {
    id: "tax-pf",
    name: "Provident Fund",
    type: "percentage",
    value: 5,
    description: "Retirement contribution deducted from payroll.",
    active: true,
  },
  {
    id: "tax-health",
    name: "Health Insurance",
    type: "fixed",
    value: 2200,
    description: "Employee medical insurance contribution.",
    active: true,
  },
  {
    id: "tax-wfh",
    name: "Remote Work Adjustment",
    type: "fixed",
    value: 1500,
    description: "Optional operational deduction for remote equipment recovery.",
    active: false,
  },
];

export const financeSalaryRecordsSeed: SalaryRecord[] = [
  {
    id: "emp-001",
    employeeId: "XR-1001",
    employeeName: "Aarav Mehta",
    department: "Engineering",
    basicSalary: 92000,
    bonus: 12000,
    allowances: 8000,
    paymentStatus: "Paid",
    taxes: [
      {
        id: "aarav-tax-1",
        definitionId: "tax-income",
        name: "Income Tax",
        type: "percentage",
        value: 10,
        description: "Standard income tax applied to gross salary.",
        active: true,
      },
      {
        id: "aarav-tax-2",
        definitionId: "tax-pf",
        name: "Provident Fund",
        type: "percentage",
        value: 5,
        description: "Retirement contribution deducted from payroll.",
        active: true,
      },
    ],
  },
  {
    id: "emp-002",
    employeeId: "XR-1002",
    employeeName: "Ishita Rao",
    department: "Design",
    basicSalary: 78000,
    bonus: 9000,
    allowances: 6000,
    paymentStatus: "Processing",
    taxes: [
      {
        id: "ishita-tax-1",
        definitionId: "tax-income",
        name: "Income Tax",
        type: "percentage",
        value: 8,
        description: "Reduced tax slab approved for this band.",
        active: true,
      },
      {
        id: "ishita-tax-2",
        definitionId: "tax-health",
        name: "Health Insurance",
        type: "fixed",
        value: 2200,
        description: "Employee medical insurance contribution.",
        active: true,
      },
    ],
  },
  {
    id: "emp-003",
    employeeId: "XR-1003",
    employeeName: "Rohan Kapoor",
    department: "Operations",
    basicSalary: 64000,
    bonus: 7000,
    allowances: 5000,
    paymentStatus: "Pending",
    taxes: [
      {
        id: "rohan-tax-1",
        definitionId: "tax-pf",
        name: "Provident Fund",
        type: "percentage",
        value: 4,
        description: "Retirement contribution deducted from payroll.",
        active: true,
      },
    ],
  },
  {
    id: "emp-004",
    employeeId: "XR-1004",
    employeeName: "Neha Sharma",
    department: "Human Resources",
    basicSalary: 71000,
    bonus: 6000,
    allowances: 4500,
    paymentStatus: "Paid",
    taxes: [],
  },
  {
    id: "emp-005",
    employeeId: "XR-1005",
    employeeName: "Kabir Sen",
    department: "Finance",
    basicSalary: 88000,
    bonus: 11000,
    allowances: 9000,
    paymentStatus: "Paid",
    taxes: [
      {
        id: "kabir-tax-1",
        definitionId: "tax-income",
        name: "Income Tax",
        type: "percentage",
        value: 11,
        description: "Senior payroll band income deduction.",
        active: true,
      },
      {
        id: "kabir-tax-2",
        definitionId: "tax-health",
        name: "Health Insurance",
        type: "fixed",
        value: 2200,
        description: "Employee medical insurance contribution.",
        active: true,
      },
    ],
  },
];
