export const PERMISSIONS = {
  VIEW_DASHBOARD: "view.dashboard",
  VIEW_ADMIN_OVERVIEW: "view.dashboard.admin_overview",
  VIEW_HR_OVERVIEW: "view.dashboard.hr_overview",
  VIEW_MY_WORKSPACE: "view.dashboard.my_workspace",
  VIEW_SETTINGS: "view.settings",
  ATTENDANCE_PANEL_VIEW: "attendance.panel.view",
  ATTENDANCE_VIEW_CLOCKS: "attendance.view.clocks",
  ATTENDANCE_VIEW_PERCENT: "attendance.view.percent",
  ATTENDANCE_VIEW_NOTES: "attendance.view.notes",
  LEAVE_APPLY: "leave.apply",
  LEAVE_VIEW_MY: "leave.view.my",
  LEAVE_CANCEL_MY: "leave.cancel.my",
  LEAVE_VIEW_BALANCE: "leave.view.balance",
  LEAVE_REQUESTS_VIEW: "leave.requests.view",
  LEAVE_REQUESTS_APPROVE: "leave.requests.approve",
  LEAVE_REQUESTS_REJECT: "leave.requests.reject",
  LEAVE_CALENDAR_VIEW: "leave.calendar.view",
  LEAVE_POLICY_VIEW: "leave.policy.view",
  LEAVE_POLICY_MANAGE: "leave.policy.manage",
  LEAVE_REPORTS_VIEW: "leave.reports.view",
  LEAVE_REPORTS_EXPORT: "leave.reports.export",
  VIEW_EMPLOYEES: "view.employees",
  VIEW_EMPLOYEE_STATUS: "view.employees.status",
  CREATE_EMPLOYEE: "create.employees",
  EDIT_EMPLOYEE: "edit.employees",
  DELETE_EMPLOYEE: "delete.employees",
  TOGGLE_EMPLOYEE_STATUS: "toggle.employees.status",
  VIEW_ADMIN_USERS: "view.admin.users",
  VIEW_ADMIN_TICKETS: "view.admin.tickets",
  VIEW_ADMIN_ATTENDANCE: "view.admin.attendance",
  VIEW_ADMIN_ROLES: "view.admin.roles",
  VIEW_ADMIN_FINANCE: "view.admin.finance",
  VIEW_SHIFT_MANAGEMENT: "view.shift.management",
  VIEW_USER_FINANCE: "view.user.finance",
  MANAGE_USERS: "manage.users",
  MANAGE_ROLES: "manage.roles",
  MANAGE_TICKETS: "manage.tickets",
  MANAGE_EXPENSES: "manage.expenses",
  MANAGE_SHIFT_MANAGEMENT: "manage.shift.management",
  VIEW_HR_EMPLOYEES: "view.hr.employees",
  VIEW_USER_TASKS: "view.user.tasks",
  ATTENDANCE_CLOCK: "attendance.clock",
  ATTENDANCE_REGULARIZATION_REQUEST: "attendance.regularization.request",
  ATTENDANCE_REGULARIZATION_REVIEW: "attendance.regularization.review",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_LABELS: Record<PermissionKey, string> = {
  [PERMISSIONS.VIEW_DASHBOARD]: "Dashboard",
  [PERMISSIONS.VIEW_ADMIN_OVERVIEW]: "Admin Overview",
  [PERMISSIONS.VIEW_HR_OVERVIEW]: "HR Overview",
  [PERMISSIONS.VIEW_MY_WORKSPACE]: "My Workspace",
  [PERMISSIONS.VIEW_SETTINGS]: "Settings",
  [PERMISSIONS.LEAVE_APPLY]: "Apply Leave",
  [PERMISSIONS.LEAVE_VIEW_MY]: "My Leaves",
  [PERMISSIONS.LEAVE_CANCEL_MY]: "Cancel Leave",
  [PERMISSIONS.LEAVE_VIEW_BALANCE]: "Leave Balance",
  [PERMISSIONS.LEAVE_REQUESTS_VIEW]: "Leave Requests",
  [PERMISSIONS.LEAVE_REQUESTS_APPROVE]: "Approve Leave",
  [PERMISSIONS.LEAVE_REQUESTS_REJECT]: "Reject Leave",
  [PERMISSIONS.LEAVE_CALENDAR_VIEW]: "Leave Calendar",
  [PERMISSIONS.LEAVE_POLICY_VIEW]: "Leave Policy",
  [PERMISSIONS.LEAVE_POLICY_MANAGE]: "Manage Leave Policy",
  [PERMISSIONS.LEAVE_REPORTS_VIEW]: "Leave Reports",
  [PERMISSIONS.LEAVE_REPORTS_EXPORT]: "Export Leave Reports",
  [PERMISSIONS.VIEW_EMPLOYEES]: "Employees",
  [PERMISSIONS.VIEW_EMPLOYEE_STATUS]: "Status",
  [PERMISSIONS.CREATE_EMPLOYEE]: "Create",
  [PERMISSIONS.EDIT_EMPLOYEE]: "Edit",
  [PERMISSIONS.DELETE_EMPLOYEE]: "Delete",
  [PERMISSIONS.TOGGLE_EMPLOYEE_STATUS]: "Enable/Disable",
  [PERMISSIONS.VIEW_ADMIN_USERS]: "Employees (Legacy Admin)",
  [PERMISSIONS.VIEW_ADMIN_TICKETS]: "Tickets",
  [PERMISSIONS.ATTENDANCE_PANEL_VIEW]: "Attendance Panel",
  [PERMISSIONS.ATTENDANCE_VIEW_CLOCKS]: "Attendance: Clock In/Out",
  [PERMISSIONS.ATTENDANCE_VIEW_PERCENT]: "Attendance: Percentage",
  [PERMISSIONS.ATTENDANCE_VIEW_NOTES]: "Attendance: Notes",
  [PERMISSIONS.VIEW_ADMIN_ATTENDANCE]: "Attendance Panel (Legacy)",
  [PERMISSIONS.VIEW_ADMIN_ROLES]: "Role Management",
  [PERMISSIONS.VIEW_ADMIN_FINANCE]: "Finance",
  [PERMISSIONS.VIEW_SHIFT_MANAGEMENT]: "Shift Management (View)",
  [PERMISSIONS.VIEW_USER_FINANCE]: "My Finance",
  [PERMISSIONS.MANAGE_USERS]: "Manage Employees",
  [PERMISSIONS.MANAGE_ROLES]: "Manage Roles",
  [PERMISSIONS.MANAGE_TICKETS]: "Manage Tickets",
  [PERMISSIONS.MANAGE_EXPENSES]: "Manage Expenses",
  [PERMISSIONS.MANAGE_SHIFT_MANAGEMENT]: "Shift Management (Manage)",
  [PERMISSIONS.VIEW_HR_EMPLOYEES]: "Employees (Legacy HR)",
  [PERMISSIONS.VIEW_USER_TASKS]: "My Tasks",
  [PERMISSIONS.ATTENDANCE_CLOCK]: "Attendance Clock",
  [PERMISSIONS.ATTENDANCE_REGULARIZATION_REQUEST]: "Attendance: Raise Regularization",
  [PERMISSIONS.ATTENDANCE_REGULARIZATION_REVIEW]: "Attendance: Review Regularization",
};

export const PERMISSION_GROUPS: Array<{
  id: string;
  title: string;
  permissions: PermissionKey[];
}> = [
  {
    id: "dashboard",
    title: "Dashboard",
    permissions: [
      PERMISSIONS.VIEW_DASHBOARD,
      PERMISSIONS.VIEW_ADMIN_OVERVIEW,
      PERMISSIONS.VIEW_HR_OVERVIEW,
      PERMISSIONS.VIEW_MY_WORKSPACE,
    ],
  },
  {
    id: "settings",
    title: "Settings",
    permissions: [PERMISSIONS.VIEW_SETTINGS],
  },
  {
    id: "employees",
    title: "Employees",
    permissions: [
      PERMISSIONS.VIEW_EMPLOYEES,
      PERMISSIONS.VIEW_EMPLOYEE_STATUS,
      PERMISSIONS.CREATE_EMPLOYEE,
      PERMISSIONS.EDIT_EMPLOYEE,
      PERMISSIONS.DELETE_EMPLOYEE,
      PERMISSIONS.TOGGLE_EMPLOYEE_STATUS,
      PERMISSIONS.VIEW_ADMIN_USERS,
      PERMISSIONS.MANAGE_USERS,
      PERMISSIONS.VIEW_HR_EMPLOYEES,
    ],
  },
  {
    id: "leave",
    title: "Leave",
    permissions: [
      PERMISSIONS.LEAVE_APPLY,
      PERMISSIONS.LEAVE_VIEW_MY,
      PERMISSIONS.LEAVE_CANCEL_MY,
      PERMISSIONS.LEAVE_VIEW_BALANCE,
      PERMISSIONS.LEAVE_REQUESTS_VIEW,
      PERMISSIONS.LEAVE_REQUESTS_APPROVE,
      PERMISSIONS.LEAVE_REQUESTS_REJECT,
      PERMISSIONS.LEAVE_CALENDAR_VIEW,
      PERMISSIONS.LEAVE_POLICY_VIEW,
      PERMISSIONS.LEAVE_POLICY_MANAGE,
      PERMISSIONS.LEAVE_REPORTS_VIEW,
      PERMISSIONS.LEAVE_REPORTS_EXPORT,
    ],
  },
  {
    id: "tickets",
    title: "Tickets",
    permissions: [PERMISSIONS.VIEW_ADMIN_TICKETS, PERMISSIONS.MANAGE_TICKETS],
  },
  {
    id: "attendance",
    title: "Attendance",
    permissions: [
      PERMISSIONS.ATTENDANCE_PANEL_VIEW,
      PERMISSIONS.ATTENDANCE_VIEW_CLOCKS,
      PERMISSIONS.ATTENDANCE_VIEW_PERCENT,
      PERMISSIONS.ATTENDANCE_VIEW_NOTES,
      PERMISSIONS.VIEW_ADMIN_ATTENDANCE,
      PERMISSIONS.ATTENDANCE_CLOCK,
      PERMISSIONS.ATTENDANCE_REGULARIZATION_REQUEST,
      PERMISSIONS.ATTENDANCE_REGULARIZATION_REVIEW,
    ],
  },
  {
    id: "roles",
    title: "Roles",
    permissions: [PERMISSIONS.VIEW_ADMIN_ROLES, PERMISSIONS.MANAGE_ROLES],
  },
  {
    id: "finance",
    title: "Finance",
    permissions: [PERMISSIONS.VIEW_ADMIN_FINANCE, PERMISSIONS.VIEW_USER_FINANCE, PERMISSIONS.MANAGE_EXPENSES],
  },
  {
    id: "shifts",
    title: "Shifts",
    permissions: [PERMISSIONS.VIEW_SHIFT_MANAGEMENT, PERMISSIONS.MANAGE_SHIFT_MANAGEMENT],
  },
  {
    id: "tasks",
    title: "Tasks",
    permissions: [PERMISSIONS.VIEW_USER_TASKS],
  },
];
